// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package serviceGroup

import (
	"github.com/dickynovanto1103/dependencyInjectionGolang/httpClient"
	"github.com/dickynovanto1103/dependencyInjectionGolang/logger"
)

// Injectors from container.go:

func CreateServiceGroup() *ServiceGroup {
	loggerLogger := &logger.Logger{}
	httpClientHttpClient := httpClient.NewHttpClient(loggerLogger)
	serviceGroup := NewServiceGroup(loggerLogger, httpClientHttpClient)
	return serviceGroup
}
