// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/dickynovanto1103/dependencyInjectionGolang/httpClient"
	"github.com/dickynovanto1103/dependencyInjectionGolang/logger"
	"github.com/dickynovanto1103/dependencyInjectionGolang/serviceGroup"
)

// Injectors from container.go:

func CreateServiceGroup() *serviceGroup.ServiceGroup {
	logger := &logger.Logger{}
	httpClient := httpClient.NewHttpClient(logger)
	serviceGroup := serviceGroup.NewServiceGroup(logger, httpClient)
	return serviceGroup
}
