// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from container.go:

func CreateServiceGroup() *ServiceGroup {
	logger := &Logger{}
	httpClient := NewHttpClient(logger)
	serviceGroup := NewServiceGroup(logger, httpClient)
	return serviceGroup
}
